server:
    port: 9000
spring:
    profiles:
        active: dev, base-addi
    devtools:
        livereload:
            enabled: true
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:XE
        username: c##fund
        password: FUND

    security:
        user:
            name: user
            password: 1234


    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
            # yeoooo : ? ? create ? update ?? create-drop ?? ?????
        #        defer-datasource-initialization: true
        generate-ddl: true

# sql init script
#    sql:
#        init:
#            platform: oracle
#            encoding: UTF-8
#            mode: always
custom:
    genFileDirPath: c:/Temp/fundFun

